version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: beybladetournamentsoftware
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: